# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk-sid

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install
      - run: cd functions && yarn install && cd ..

      - save_cache:
          paths:
            - node_modules
            - functions/node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: yarn tslint
      - run: yarn test:compile
      - run: yarn firebase setup:emulators:firestore
      - run:
          command: yarn firebase serve --only firestore
          background: true
      - run: yarn test:ci
      - persist_to_workspace:
          root: .
          paths:
            - .

  deploy_development:
    docker:
      - image: circleci/openjdk:11-jdk-sid
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: .
      - run: yarn build
      - run: yarn firebase deploy --project development --token "$FIREBASE_TOKEN_DEVELOPMENT"

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - build
      - deploy_development:
          requires:
            - build
          filters:
            branches:
              only: master
